services:
  app:
    build:
      context: .
    working_dir: /workspace
    volumes:
      - .:/workspace
    command: runext -r
  bash:
    build:
      context: .
    working_dir: /workspace
    volumes:
      - .:/workspace
    command: /bin/bash
