version: 1.0.0
openapi: /bypass/openapi.json
events:
  - event: platform.commerce.order.status_changed
    condition: "and(eq(status,Processing),eq(product.id,{{ settings.product_id }}))"
    path: "/api/v1/events/orders"
    task: true
plugs:
  - id: subs-actions
    name: Subscriptions Actions Demo
    description: Check sockets
    icon: adobe.png
    socket: portal.commerce.subscriptions.actions
    href: "/static/index.js"
webhooks:
  - type: validatePurchaseOrderDraft
    description: "Draft order validation"
    path: /api/v1/validation/orders
    criteria:
      product.id: "{{ settings.product_id }}"
deferrables:
  - path: "/api/v1/tasks/synchronize"
    method: GET
    description: "Run a background synchronization task"
schedules:
  - path: /api/v1/cron/dojob
    id: my.cron.job
    name: "My cron job"
    description: "Test cron job"
    cron: "* * * * *"
