version: 1.0.0
openapi: /bypass/openapi.json
events:
  - event: platform.commerce.order.status_changed
    condition: "and(eq(status,Processing),eq(product.id,{{ settings.product_id }}))"
    path: "/events/commerce/orders"
    task: true
