# common extension's settings

env_domain: "platform.softwareone.com"
base_url: "@format https://api.{this.env_domain}/public/v1"
extension_id: "EXT-0000-0000"  # replace with your extension id
extension_domain: "@format ext.{this.env_domain}"
extension_fqdn: "@jinja {{this.extension_id | lower}}.{{this.extension_domain}}"
rows_per_page: 50

# extension's specific settings
product_id: PRD-0000-0000  # replace with your product id
